version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: alexejk/portal
analyze:
  modules:
  - name: github.com/alexejk/portal
    type: go
    target: github.com/alexejk/portal
    path: .
