name: FOSSA

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: FOSSA License check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install FOSSA Client
      run: |
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash

    - name: Run FOSSA Analyze
      env: # Or as an environment variable
        FOSSA_API_KEY: ${{ secrets.FossaApiKey }}
      run: |
        fossa analyze
